version: '3'

services:
  mnginx:
    build:
      dockerfile: ./mnginx/Dockerfile
      context: .
    ports:
      - "80:80"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    # environment:
    #   RABBITMQ_DEFAULT_USER: "meli"
    #   RABBITMQ_DEFAULT_PASS: "meli"
    #   RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"

  mutantornot:
    build:
      dockerfile: ./mutantornot/Dockerfile
      context: .
    ports:
      # local_port:container_port
      - "8081:8081"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  dnastats:
    build: 
      dockerfile: ./dnastats/Dockerfile
      context: .
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - mongodb
    links:
      - rabbitmq
      - mongodb
