version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  mnginx:
    build:
      dockerfile: ./mnginx/Dockerfile
      context: .
    ports:
      - "80:80"
    depends_on:
      - mutant
      - dna
  mutant:
    build:
      dockerfile: ./mutantornot/Dockerfile
      context: .
    ports:
      # local_port:container_port
      - "8081:8081"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  dna:
    build: 
      dockerfile: ./dnastats/Dockerfile
      context: .
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - mongodb
    links:
      - rabbitmq
      - mongodb
