apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnginx
  labels:
    app: mnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnginx
  template:
    metadata:
      labels:
        app: mnginx
    spec:
      containers:
      - image: aelias/mnginx:1.0.0
        name: mnginx
        resources:
            limits:
              memory: "32Mi"
              cpu: "200m"        
        ports:
        - name: mnginx
          containerPort: 80
          protocol: TCP

