apiVersion: v1
kind: Service
metadata:
  name: mutant
  labels:
    app: mutant
spec:
  ports:
  - name: "mutant"
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mutant
  type: ClusterIP
