apiVersion: v1
kind: Service
metadata:
  name: dna
  labels:
    app: dna
spec:
  ports:
  - name: "dna"
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: dna
  type: ClusterIP
