apiVersion: apps/v1
kind: Deployment
metadata:
  name: dna
  labels:
    app: dna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dna
  template:
    metadata:
      labels:
        app: dna
    spec:
      containers:
      - image: aelias/dnastats
        name: dna
        resources:
            limits:
              memory: "32Mi"
              cpu: "200m"        
        env:
          - name: RABBIT_CONN_STRING
            value: "amqp://guest:guest@rabbitmq:5672"
          - name: MONGO_CONN_STRING
            value: "mongodb"
          - name: GIN_MODE
            value: "release"
        ports:
          - containerPort: 8082
            protocol: TCP
